### PR TITLE
updating SAT version having security fix

### PR DESCRIPTION
**Pull request by shivaprasad-metimath**
IM:CRAYSAT-1795
Reviewer:Ryan

## Summary and Scope

CRAYSAT-1795 Changes to address security vulnerabilities
Hence upgrading the version

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [CRAYSAT-1795](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1795)

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * MUG

### Test description:

SAT commands have been tested and looks good without any issues

## Risks and Mitigations

Low risk

## Pull Request Checklist

- [x] Version number(s) incremented, if applicable
- [x] Copyrights updated
- [x] License file intact
- [x] Target branch correct
- [x] CHANGELOG.md updated
- [x] Testing is appropriate and complete, if applicable
- [x] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Review by haasken-hpe — APPROVED** [review]
Looks good to me. I restarted the failed Jenkins pipeline. It looks like it failed because the 3.21.8 build of cray-sat was not yet available. I expect it should work this time.

**Comment by haasken-hpe** [comment]
It looks like the build of cray-sat:3.21.8 actually failed in the release/3.21 branch of the Jenkins multibranch pipeline here: https://jenkins.algol60.net/job/Cray-HPE/job/sat/job/release%252F3.21/10/console

It may be a transient failure with Snyk scanning. I'm taking a look.

**Comment by haasken-hpe** [comment]
The cray-sat:3.21.8 build failure has been resolved with another rebuild. We're not sure at the moment what went wrong. I'll kick off another build of this branch now.

**Comment by haasken-hpe** [comment]
The build of this branch ran into a couple other intermittent issues. Two rebuilds were required to get it to work. We'll have to look into this if it keeps occurring.

**Comment by shivaprasad-metimath** [comment]
Yaa it was strange for me that such a long time was needed for the new version visibility

**Pull request merged**
